Worksheet_1
Ayusha_Karki
2461859
L5CG11
#To do Task

Problem 1

In [40]:
#1
import numpy as np

arr_empty = np.empty((2,2))
arr_empty


array([[2.5e-323, 1.5e-323],
       [9.9e-324, 4.9e-324]])

In [41]:
#2
ones_arr = np.ones((4,2))
ones_arr


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [42]:
#3
full_array = np.full((3,3), 7)
full_array



array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [43]:
#4
given = np.array([[1,2,3],[4,5,6]])
zeros_like_arr = np.zeros_like(given)
zeros_like_arr


array([[0, 0, 0],
       [0, 0, 0]])

In [44]:
#5
ones_like_arr = np.ones_like(given)
ones_like_arr



array([[1, 1, 1],
       [1, 1, 1]])

In [45]:
#6
new_list = [1,2,3,4]
np_array = np.array(new_list)
np_array

array([1, 2, 3, 4])

Problem 2


In [46]:
#1
arr = np.arange(10,50)
arr


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [47]:
#2
mat_3x3 = np.arange(9).reshape(3,3)
mat_3x3


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [48]:
#3
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
#4
rand_arr = np.random.random(30)
rand_arr.mean()


np.float64(0.5166403449252128)

In [50]:
#5
rand_10 = np.random.random((10,10))
rand_10.min(), rand_10.max()


(np.float64(0.005041430037566297), np.float64(0.9906099047437508))

In [51]:
#6
z = np.zeros(10)
z[4] = 1
z


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [52]:
#7
arr = np.array([1,2,0,0,4,0])
arr[::-1]


array([0, 4, 0, 0, 2, 1])

In [53]:
#8
m = np.ones((5,5))
m[1:-1,1:-1] = 0
m



array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [54]:
#9
m = np.ones((5,5))
m[1:-1,1:-1] = 0
m


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Problem 3

In [55]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])



In [56]:
#1
x + y



array([[ 6,  8],
       [10, 13]])

In [57]:
#2
x - y


array([[-4, -4],
       [-4, -3]])

In [58]:
#3
x * 3


array([[ 3,  6],
       [ 9, 15]])

In [59]:
#4
x**2


array([[ 1,  4],
       [ 9, 25]])

In [60]:
#5
np.dot(v,w)
np.dot(x,v)
np.dot(x,y)


array([[19, 22],
       [50, 58]])

In [61]:
#6
np.vstack((x,y))


array([[1, 2],
       [3, 5],
       [5, 6],
       [7, 8]])

In [62]:

np.column_stack((v,w))


array([[ 9, 11],
       [10, 12]])

In [63]:
#7
np.concatenate((x,v))


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

x is 2×2 (2D)
v is 1D (size 2)
They cannot be concatenated because their dimensions do not match (2D vs 1D)

Problem 4

In [ ]:

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])


In [ ]:
#1
np.dot(A, np.linalg.inv(A))



In [ ]:
#2
AB = np.dot(A,B)
BA = np.dot(B,A)
AB, BA


In [ ]:
#3
AB = np.dot(A,B)
lhs = AB.T
rhs = np.dot(B.T, A.T)
lhs, rhs


Linear equation

In [ ]:
#Matrix form AX = B
A = np.array([[2,-3,1],
              [1,-1,2],
              [3,1,-1]])

B = np.array([-1,-3,9])


In [ ]:
X = np.dot(np.linalg.inv(A), B)
X


In [ ]:
np.linalg.solve(A,B)
